-- Run this entire file once in Supabase: SQL Editor > New query > Run.
create table if not exists public.events (
  event_id bigint generated by default as identity primary key,
  event_name text not null,
  event_date date not null,
  start_time text not null,
  end_time text not null,
  start_sort time not null,
  location text not null,
  season text not null,
  description text not null default '',
  special_notes text not null default '',
  details_key text not null default '',
  slots_required integer not null default 2 check (slots_required between 1 and 20)
);

create table if not exists public.signups (
  signup_id uuid primary key default gen_random_uuid(),
  event_id bigint not null references public.events(event_id) on delete cascade,
  slot_number integer not null check (slot_number > 0),
  last_name text not null check (length(trim(last_name)) between 1 and 80),
  signed_up_at timestamptz not null default now(),
  unique(event_id, slot_number)
);

-- This function locks the event row, counts available positions, and assigns
-- the first open slot in one transaction. Concurrent requests cannot overbook.
create or replace function public.claim_next_slot(p_event_id bigint, p_last_name text)
returns setof public.signups
language plpgsql
security definer
set search_path = public
as $$
declare
  v_required integer;
  v_slot integer;
begin
  select slots_required into v_required from public.events
  where event_id = p_event_id for update;
  if v_required is null then raise exception 'Event not found'; end if;
  select s into v_slot from generate_series(1, v_required) s
  where not exists (select 1 from public.signups x where x.event_id=p_event_id and x.slot_number=s)
  order by s limit 1;
  if v_slot is null then return; end if;
  return query insert into public.signups(event_id, slot_number, last_name)
    values (p_event_id, v_slot, trim(p_last_name)) returning *;
end;
$$;

alter table public.events enable row level security;
alter table public.signups enable row level security;
drop policy if exists "public read events" on public.events;
drop policy if exists "public read signups" on public.signups;
drop policy if exists "public delete signups" on public.signups;
create policy "public read events" on public.events for select to anon using (true);
create policy "public read signups" on public.signups for select to anon using (true);
create policy "public delete signups" on public.signups for delete to anon using (true);
grant usage on schema public to anon;
grant select on public.events, public.signups to anon;
grant delete on public.signups to anon;
grant execute on function public.claim_next_slot(bigint,text) to anon;

truncate table public.signups;
truncate table public.events restart identity cascade;
insert into public.events(event_name,event_date,start_time,end_time,start_sort,location,season,description,special_notes,details_key) values
('SUS Admissions Directors Tour','2026-09-10','7:30 a.m.','2:00 p.m.','07:30','University Center','FALL 2026 · RECRUITMENT','A collaborative event connecting Florida high school counselors with representatives from all 12 public universities.','',''),
('Explore UNF','2026-10-24','9:00 a.m.','2:00 p.m.','09:00','Fine Arts Center','FALL 2026 · RECRUITMENT','A large-scale campus preview for prospective students and families, showcasing academic programs, resources, and student life.','STEM on the Lawn runs concurrently at the Amphitheater from 10:30 a.m. to 2:30 p.m. Coordinate staffing so families can move easily between activities.','explore'),
('Explore UNF','2026-11-14','9:00 a.m.','2:00 p.m.','09:00','Fine Arts Center','FALL 2026 · RECRUITMENT','A large-scale campus preview for prospective students and families, showcasing academic programs, resources, and student life.','Homecoming parade runs 9:30–10:30 a.m.; Party in the Plaza follows; basketball begins at 2:00 p.m. Plan for a merged, higher-traffic resource-fair window.','explore'),
('Fall 2026 Commencement','2026-12-11','Schedule TBA','','00:00','Location TBA','FALL 2026 · COMMENCEMENT','Faculty participation in Fall 2026 Commencement. The event schedule and location will be added when announced.','',''),
('UNF Scholars Day','2027-01-30','9:00 a.m.','2:00 p.m.','09:00','Fine Arts Center','SPRING 2027 · YIELD','A premier admitted-student event combining Admitted Ospreys Day, Hicks Honors College Day, and Celebration of Scholars.','',''),
('Admitted Ospreys Day — Morning','2027-03-06','9:00 a.m.','1:00 p.m.','09:00','Student Union','SPRING 2027 · YIELD','A key yield event helping admitted students and their families take the next step toward enrolling at UNF.','',''),
('Admitted Ospreys Day — Afternoon','2027-03-06','11:00 a.m.','3:00 p.m.','11:00','Student Union','SPRING 2027 · YIELD','A key yield event helping admitted students and their families take the next step toward enrolling at UNF.','',''),
('Admitted Ospreys Day','2027-04-17','9:00 a.m.','2:00 p.m.','09:00','Fine Arts Center','SPRING 2027 · YIELD','A key yield event helping admitted students and their families take the next step toward enrolling at UNF.','',''),
('Spring 2027 Commencement','2027-04-30','Schedule TBA','','00:00','Location TBA','SPRING 2027 · COMMENCEMENT','Faculty participation in Spring 2027 Commencement. The event schedule and location will be added when announced.','',''),
('Admitted Ospreys Day — Morning','2027-05-01','9:00 a.m.','1:00 p.m.','09:00','Student Union','SPRING 2027 · YIELD','A key yield event helping admitted students and their families take the next step toward enrolling at UNF.','',''),
('Admitted Ospreys Day — Afternoon','2027-05-01','11:00 a.m.','3:00 p.m.','11:00','Student Union','SPRING 2027 · YIELD','A key yield event helping admitted students and their families take the next step toward enrolling at UNF.','','');
